In [2]:
import pandas as pd

# working with Json

In [3]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [4]:
pd.read_json('https://www.floatrates.com/daily/usd.json')

,aud,cad,chf,cny,eur,gbp,hkd,idr,inr,jpy,...,vuv,wst,xcd,xcg,xpf,yer,zmw,irr,lak,syp
code,AUD,CAD,CHF,CNY,EUR,GBP,HKD,IDR,INR,JPY,...,VUV,WST,XCD,XCG,XPF,YER,ZMW,IRR,LAK,SYP
alphaCode,AUD,CAD,CHF,CNY,EUR,GBP,HKD,IDR,INR,JPY,...,VUV,WST,XCD,XCG,XPF,YER,ZMW,IRR,LAK,SYP
numericCode,036,124,756,156,978,826,344,360,356,392,...,548,882,951,532,953,886,967,364,418,760
name,Australian Dollar,Canadian Dollar,Swiss Franc,Chinese Yuan,Euro,U.K. Pound Sterling,Hong Kong Dollar,Indonesian Rupiah,Indian Rupee,Japanese Yen,...,Vanuatu vatu,Samoan tala,East Caribbean Dollar,Caribbean guilder,CFP Franc,Yemeni rial,Zambian kwacha,Iranian rial,Lao kip,Syrian pound
rate,1.512517,1.396178,0.800726,7.07089,0.857223,0.749499,7.782683,16640.420852,90.0001,154.965392,...,121.138351,2.777902,2.699983,1.789988,102.290159,238.367907,23.06729,42247.674419,21756.287425,11043.465046
date,"Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT",...,"Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT","Thu, 4 Dec 2025 21:55:11 GMT"
inverseRate,0.66115,0.716241,1.248866,0.141425,1.166558,1.334225,0.12849,0.00006,0.011111,0.006453,...,0.008255,0.359984,0.370373,0.558663,0.009776,0.004195,0.043351,0.000024,0.000046,0.000091

# working with SQL

In [5]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\sangr\anaconda3\lib\site-packages (9.3.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import mysql.connector

In [10]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world'
)

In [11]:
pd.read_sql_query("SELECT * FROM city",conn)

C:\Users\sangr\AppData\Local\Temp\ipykernel_14728\2215102799.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [12]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

C:\Users\sangr\AppData\Local\Temp\ipykernel_14728\2335966076.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [13]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'USA'",conn)

C:\Users\sangr\AppData\Local\Temp\ipykernel_14728\3992278021.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'USA'",conn)

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]

In [14]:
pd.read_sql_query("SELECT * FROM city WHERE Population > 100000",conn)

C:\Users\sangr\AppData\Local\Temp\ipykernel_14728\2219331164.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE Population > 100000",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
3553  4074            Gaza         PSE           Gaza      353632
3554  4075      Khan Yunis         PSE     Khan Yunis      123175
3555  4076          Hebron         PSE         Hebron      119401
3556  4077        Jabaliya         PSE     North Gaza      113901
3557  4078          Nablus         PSE         Nablus      100231

[3558 rows x 5 columns]

In [15]:
pd.read_sql_query("SELECT * FROM city WHERE Population < 50000",conn)

C:\Users\sangr\AppData\Local\Temp\ipykernel_14728\2746997638.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE Population < 50000",conn)

      ID                Name CountryCode          District  Population
0     33          Willemstad         ANT           Curaçao        2345
1     53              Tafuna         ASM           Tutuila        5200
2     54            Fagatogo         ASM           Tutuila        2323
3     55    Andorra la Vella         AND  Andorra la Vella       21189
4     61          South Hill         AIA                 –         961
..   ...                 ...         ...               ...         ...
73  3424            Funafuti         TUV          Funafuti        4600
74  3536            Mata-Utu         WLF            Wallis        1137
75  3537           Port-Vila         VUT             Shefa       33700
76  3538  Città del Vaticano         VAT                 –         455
77  4067    Charlotte Amalie         VIR         St Thomas       13000

[78 rows x 5 columns]

In [17]:
# here we storing our SQL data TAble into variable
df  = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

C:\Users\sangr\AppData\Local\Temp\ipykernel_14728\2911018930.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df  = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

In [18]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]