In [1]:
import numpy as np
import pandas as pd

In [2]:
df  =  pd.read_csv('customer.csv')

In [3]:
df.sample(5)

#Categorical_cols --> gender	review	education	purchased 

# gender	--> Nominal Categorical  --> One Hot Encoder
# review    --> Ordinal Categorical  --> Ordinal Encoder
# education --> Ordinal Categorical  --> Ordinal Encoder
# purchased --> Nominal Categorical --> Label Encoder

    age  gender   review education purchased
15   75    Male     Poor        UG        No
5    31  Female  Average    School       Yes
48   39  Female     Good        UG       Yes
24   16  Female  Average        PG       Yes
22   18  Female     Poor        PG       Yes

In [4]:
df = df.iloc[: ,2:]  # All Rows & 2,3,4 Cols

In [24]:
df.head(15)

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes

# Train Test Split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1],test_size = 0.2)

In [7]:
X_train

     review education
36     Good        UG
34  Average    School
2      Good        PG
32  Average        UG
16     Poor        UG
37  Average        PG
11     Good        UG
33     Good        PG
27     Poor        PG
19     Poor        PG
7      Poor    School
12     Poor    School
46     Poor        PG
45     Poor        PG
0   Average    School
4   Average        UG
43     Poor        PG
3      Good        PG
28     Poor    School
47     Good        PG
35     Poor    School
8   Average        UG
1      Poor        UG
15     Poor        UG
14     Poor        PG
22     Poor        PG
49     Good        UG
48     Good        UG
44  Average        UG
40     Good    School
29  Average        UG
31     Poor    School
23     Good    School
39     Poor        PG
13  Average    School
9      Good        UG
38     Good    School
21  Average        PG
24  Average        PG
18     Good    School

# Ordinal Encoding

## Converts Categorical data into ordered Numeric Data

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
oe = OrdinalEncoder(categories = [['Poor', 'Average','Good'],['School','UG','PG']])

## If we don't give the proper ordered categories it will select randomly

In [12]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

#  Data Transformation

In [13]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [14]:
X_train

array([[2., 1.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.]])

In [15]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoding

## Convert O/P labeled data into Numerical Data

- Encode target labels with value between 0 and n_classes-1.

- This transformer should be used to encode target values, i.e. y, and not the input X

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le  = LabelEncoder()

## here we can't give order to categories(like Ordinal) , it will give by itself
#

In [19]:
le.fit(y_train)

LabelEncoder()

In [20]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [21]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [22]:
y_train

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0])